const SIDEBAR_LEFT_PANEL_WIDTH = 54
const SIDEBAR_RIGHT_PANEL_WIDTH = 400
export const DIMENSIONS = {
    SIDEBAR_LEFT_PANEL_WIDTH: SIDEBAR_LEFT_PANEL_WIDTH,
    SIDEBAR_RIGHT_PANEL_WIDTH: SIDEBAR_RIGHT_PANEL_WIDTH,
    SIDEBAR_WIDTH: SIDEBAR_LEFT_PANEL_WIDTH + SIDEBAR_RIGHT_PANEL_WIDTH,
    CONTENT_BOX_WIDTH: 700,
    MAIN_CONTENT_OFFSET: 25,
}
