const SIDEBAR_LEFT_PANEL_WIDTH = 54
const SIDEBAR_RIGHT_PANEL_WIDTH = 300
export const DIMENSIONS = {
    SIDEBAR_LEFT_PANEL_WIDTH: SIDEBAR_LEFT_PANEL_WIDTH,
    SIDEBAR_RIGHT_PANEL_WIDTH: SIDEBAR_RIGHT_PANEL_WIDTH,
    SIDEBAR_WIDTH: SIDEBAR_LEFT_PANEL_WIDTH + SIDEBAR_RIGHT_PANEL_WIDTH,
    CONTENT_BOX_WIDTH: 700,
    MAIN_CONTENT_OFFSET: `calc(calc(calc(100% - 54ch)/2) + ${SIDEBAR_RIGHT_PANEL_WIDTH})`,
}
