import {
  red,
  crimson,
  pink,
  mauve,
  purple,
  violet,
  indigo,
  blue,
  sky,
  skyDark,
  cyan,
  grass,
  plum,
  teal,
  green,
  lime,
  yellow,
  amber,
  orange,
  redDark,
  crimsonDark,
  pinkDark,
  purpleDark,
  violetDark,
  indigoDark,
  blueDark,
  cyanDark,
  tealDark,
  greenDark,
  limeDark,
  yellowDark,
  amberDark,
  orangeDark,
  olive,
  slate,
  slateDark,
  blackA,
  whiteA,
} from "@radix-ui/colors";

const spreadColor = (color:any, scale:any) =>
  color[`${Object.keys(color)[0].split("1")[0]}${scale}`];

const accentColor = slateDark;
const error = red;
const warning = yellow;
const success = teal;
const info = sky;

export const lightColors = {
  blackA,
  white: "#fff",
  placeholder: "#6E7588",
  secondary: blackA.blackA1,
  mydark: "hsla(263, 53%, 30%, 1.0)",
  myblack: "#1A1B1E",
  mypurple: "#5A31F4",
  neongreen: "#E5FF01",
  ...blackA,
  ...olive,
  ...violet,
  ...indigo,
  ...blue,
  ...cyan,
  ...teal,
  ...green,
  ...lime,
  ...yellow,
  ...amber,
  ...orange,
  ...mauve,
  slate,
  slateDark,
  whiteA,
  accent1: spreadColor(accentColor, 1),
  accent2: spreadColor(accentColor, 2),
  accent3: spreadColor(accentColor, 3),
  accent4: spreadColor(accentColor, 4),
  accent5: spreadColor(accentColor, 5),
  accent6: spreadColor(accentColor, 6),
  accent7: spreadColor(accentColor, 7),
  accent8: spreadColor(accentColor, 8),
  accent9: spreadColor(accentColor, 9),
  accent10: spreadColor(accentColor, 10),
  accent11: spreadColor(accentColor, 11),
  accent12: spreadColor(accentColor, 12),

  primary100: "#fdfcfe",
  primary200: "#fbfaff",
  primary300: "#f5f2ff",
  primary400: "#ede9fe",
  primary500: "#e4defc",
  primary600: "#d7cff9",
  primary700: "#c4b8f3",
  primary800: "#aa99ec",
  primary900: "#6e56cf",

  error1: spreadColor(error, 9),
  error2: spreadColor(error, 10),

  warning1: spreadColor(warning, 9),
  warning2: spreadColor(warning, 10),

  success1: spreadColor(success, 9),
  success2: spreadColor(success, 10),

  info1: spreadColor(info, 9),
  info2: spreadColor(info, 10),

  appBg: spreadColor(accentColor, 1),
  componentBg: spreadColor(accentColor, 3), // scale 12 (text variable) - 400 weight
  componentBgHover: spreadColor(accentColor, 4),
  componentBgSelected: spreadColor(accentColor, 5),
  ctaBg: spreadColor(accentColor, 4),
  ctaBgHover: spreadColor(accentColor, 5),

  text2: spreadColor(accentColor, 11),
  textReverse: spreadColor(accentColor, 4),

  layoutBorder: spreadColor(accentColor, 6),
  componentBorder: spreadColor(accentColor, 7),
  componentBorderHover: spreadColor(accentColor, 8),

  solidBg: spreadColor(accentColor, 9), //white text - 600 weight
  solidBgHover: spreadColor(accentColor, 10),

  crimson: "#f76190",
  pink: "#f65cb6",
  plum: "#d864d8",
  purple: "#bf7af0",
  violet: "#9e8cfc",
  indigo: "#849dff",
  blue: "#52a9ff",
  cyan: "#00c2d7",
  teal: "#0ac5b3",
  green: "#4cc38a",
  grass: "#63c174",
  orange: "#ff8b3e",
  brown: "#dba16e",
  crimsondark: "#481a2d",
  pinkdark: "#451a37",
  plumdark: "#3e1d40",
  purpledark: "#3a1e48",
  violetdark: "#2c2250",
  indigodark: "#1c274f",
  bluedark: "#102a4c",
  cyandark: "#07303b",
  tealdark: "#07312b",
  greendark: "#113123",
  grassdark: "#16301d",
  orangedark: "#441f04",
  browndark: "#36261e",
  inputColor: violet.violet12,
  inputHoverColor: violet.violet11,
  inputFocusColor: violet.violet11,

  inputBorderColor: "hsla(250, 100%, 75%, 0.2)",
  inputHoverBgColor: violet.violet2,

  optionHoverColor: violet.violet12,
  optionIconColor: violet.violet11,

  gradientPurple:
    "linear-gradient(135deg, ${purple.purple9} 0%, ${indigo.indigo9} 100%);",
};

export const Colors = {
  white: "#fff",
  crimson: "#f76190",
  pink: "#f65cb6",
  plum: "#d864d8",
  purple: "#bf7af0",
  violet: "#9e8cfc",
  indigo: "#849dff",
  blue: "#52a9ff",
  cyan: "#00c2d7",
  teal: "#0ac5b3",
  green: "#4cc38a",
  grass: "#63c174",
  orange: "#ff8b3e",
  brown: "#dba16e",
  crimsondark: "#481a2d",
  pinkdark: "#451a37",
  plumdark: "#3e1d40",
  purpledark: "#3a1e48",
  violetdark: "#2c2250",
  indigodark: "#1c274f",
  bluedark: "#102a4c",
  cyandark: "#07303b",
  tealdark: "#07312b",
  greendark: "#113123",
  grassdark: "#16301d",
  orangedark: "#441f04",
  browndark: "#36261e",
};
